### ISSUE TITLE
failed to get `flo-grpc`

### ISSUE THREAD

**Issue by Curlbotter** [Qeenon/Amadeus#15]
Amadeus git:(mawa) cargo build --release    
    Updating crates.io index
error: failed to get `flo-grpc` as a dependency of package `amadeus v4.3.0 (/home/navi/Amadeus)`

Caused by:
  failed to load source for dependency `flo-grpc`

Caused by:
  Unable to update /home/navi/Amadeus/crates/flo-grpc

Caused by:
  failed to read `/home/navi/Amadeus/crates/flo-grpc/Cargo.toml`

Caused by:
  No such file or directory (os error 2)

**Comment by Qeenon** [comment]
@Curlbotter that's sad...

this part is currently not open source and I'm not sure how to make it 100% optional
it's in `crates/` and it's a git submodule

for now you can run that script (I'm using it for CI) https://github.com/Qeenon/Amadeus/blob/mawa/eat-some-dirt.sh
to cut it down but, I found no better way to make something proprietary to be optional

**Comment by Qeenon** [comment]
I think I will do something with it tomorrow

**Comment by Qeenon** [comment]
@Curlbotter sorry for delay, now everything should work just fine without hacky scripts
